# Generated by Django 4.2.20 on 2025-04-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
