# Generated by Django 4.2.20 on 2025-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchase_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
