# Generated by Django 4.2.20 on 2025-04-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchase_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.TextField(null=True),
        ),
    ]
