# Generated by Django 4.2.20 on 2025-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_purchase_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
