# Generated by Django 4.2.20 on 2025-04-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='entry',
            new_name='product',
        ),
    ]
