# Generated by Django 4.2.20 on 2025-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
