# Generated by Django 4.2.20 on 2025-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_score_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user/'),
        ),
    ]
