# Generated by Django 4.2.20 on 2025-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user/'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
