# Generated by Django 4.2.20 on 2025-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_product_profile_image_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
